name: Run API Tests

on:
  workflow_dispatch:  # allows manual trigger in GitHub UI
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install app dependencies
        run: npm ci
      - name: Install Mockoon CLI
        run: npm install -g @mockoon/cli
      - name: Start Mockoon server
        run: mockoon-cli start --data mockoon/mock.json --port 5000 &
      - name: Start Mockoon server
        run: mockoon-cli start \
               --data testing/2_functional/completeness/v1.1.1/simulators/MicrowaveDeviceInventory+MockServer.json \
               --port 3002 --hostname localhost &
      - name: Swap config & disable security validation
        run: |
          # 1. Replace the real config with the test config
          cp testing/2_functional/completeness/v1.1.1/simulators/config_test.json server/database/config.json
      
          # 2. Uncomment the security validation bypass in index.js
          sed -i 's|//appCommons.openApiValidatorOptions.validateSecurity = false;|appCommons.openApiValidatorOptions.validateSecurity = false;|' server/index.js
      - name: Start Node.js app
        run: node app/index.js &
      - name: Wait for Mockoon-MWDI-Simulator and APTP
        run: |
          npx wait-on http://localhost:3002
          npx wait-on http://localhost:4009
      - name: Run Postman tests
        run: |
          newman run testing/2_functional/completeness/v1.1.1/testcases/APTP_3rd+testcase.completeness\ Copy.postman_collection.json \
            -d testing/2_functional/completeness/v1.1.1/testcases/APTP_1.1.1+data.completeness.json \
            --reporters cli



